name: Deploy to VPS

# Déclenche ce workflow à chaque push sur la branche 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the home directory
            cd ~
            # Clone or update the repository
            if [ ! -d "football-info-bot" ] ; then
              git clone https://github.com/AlexandreMessuve/football-info-bot.git
              cd football-info-bot
            else
              cd football-info-bot
              git pull
            fi
            
            # Rebuild and restart bot with Docker Compose
            # Env variables are passed directly in the command for security via GitHub Secrets
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} FOOTBALL_API_KEY=${{ secrets.FOOTBALL_API_KEY }} FOOTBALL_API_BASE_URL=${{ secrets.FOOTBALL_API_BASE_URL }} docker-compose up --build -d